import "./globals.css";
import NextTopLoader from 'nextjs-toploader';
import { getWebConfig } from "./services/getWebConfig";

export async function generateMetadata() {
  const configs = await getWebConfig();
  const config = configs.data.primary;
  
  return {
    title: config.title || "Teknik Informatika Undar Jombang",
    description: config.description || "Generated by create next app",
    openGraph: {
      title: config.title || "Teknik Informatika Undar Jombang",
      description: config.description || "Generated by create next app",
    },
  };
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-100">
        <NextTopLoader color="#4f46e5" showSpinner={true} zIndex={1600} />
        {children}
      </body>
    </html>
  );
}
