import "./globals.css";
import NextTopLoader from 'nextjs-toploader';

export const metadata = {
  title: "Teknik Informatika Undar Jombang",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-100">
        <NextTopLoader color="#4f46e5" showSpinner={true} zIndex={1600} />
        {children}
      </body>
    </html>
  );
}
